# Generated by Django 4.1.7 on 2024-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=130)),
                ("last_name", models.CharField(max_length=130)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
