# Generated by Django 4.1.7 on 2024-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
