# Generated by Django 4.1.7 on 2024-03-26 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 26, 15, 1, 45, 652781, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
